name: Count NotImplemented

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Count NotImplimented
      run: |
        echo '{"schemaVersion":1,"label":"NotImplemented Count","message":"' > .github/workflows/count.json
        find rust -type f -exec cat {} + | grep -c NotImplemented >> .github/workflows/count.json
        echo '","color":"yellow","cacheSeconds":1800}' >> .github/workflows/count.json
    - name: Commit files
      run: |
        git checkout -b ci-results
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -m "update NotImplemented Count" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        force: true 
